spring:
  application:
    name: draw-application

  datasource:
    url: jdbc:mysql://localhost:3306/draw_db
    username: user
    password: 123455678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  webSocket:
    stomp:
      endpoint: /ws

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600

app:
  base-url: http://localhost:8080